### ISSUE TITLE
Release support for laravel 11

### ISSUE THREAD

**Issue by senyahnoj** [Elhebert/laravel-sri#96]
Hello - please would it be possible to cut a release which is compatible with Laravel 11?

I am currently using version 3.2.0 which is the latest available from packagist.

Following upgrade guide here from laravel 10 to 11 https://laravel.com/docs/11.x/upgrade and do the composer update, I get a failure message:

```
$ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install elhebert/laravel-sri 3.2.0 (conflict analysis result)
    - Root composer.json requires elhebert/laravel-sri ^3.1 -> satisfiable by elhebert/laravel-sri[3.1.0, 3.2.0].
```

Thank you very much!

**Comment by thirsch** [comment]
Looks like support has been added to master already. Any plans on releasing it, @Elhebert?

**Comment by thirsch** [comment]
Just as a reference for anyone else looking into this issue: https://github.com/Elhebert/laravel-sri/issues/85#issuecomment-1708057265 - Package looks like being dead.

Personally, I did the migration to vite today. Took me about an hour and vite is so much faster then webpack/mix.

**Comment by Elhebert** [comment]
Hello,

Sorry for taking such a long time to reply. I though I had already release the new version with Laravel 11 support. I just did that. v3.3.0 is available.

I haven't use this package for a while now and since Laravel 9.x introduce Vite with SRI support. Thus I don't look as closely to this package as I should except around Laravel major updates. That's on me and I'm sorry for this. Given the first party support with Vite (that is replacing Mix) I would suggest to do what @thirsch did and to migrate to Vite.

For SRI support in Vite: https://laravel.com/docs/11.x/vite#subresource-integrity-sri.
